"""
Build the persisted, leakage-free train/val/test split for ISIC "clinical: close-up" images.
(CODEBASE_TODO P0-1, P0-2, P0-3; Student 2 plan dependency S1-1.)

Grouping: two images belong to the same group if they share a lesion_id OR a patient_id
(connected components), so no lesion and no patient appears in more than one split.
Images with neither id are their own group.

Split: StratifiedGroupKFold(n_splits=10, shuffle=True, random_state=SEED) stratified on the
benign/malignant label; folds 0-6 -> train (70%), 7 -> val (10%), 8-9 -> test (20%).
Images whose diagnosis_1 is not Benign/Malignant (Indeterminate or missing) get split="excluded"
and are never used for training or evaluation of the binary task.

Usage:
    python splits/make_isic_clinical_split.py            # writes splits/isic_clinical_v1.csv + report
"""
import argparse
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedGroupKFold, train_test_split

SEED = 42
LABEL_MAP = {"Benign": 0, "Malignant": 1}
TRAIN_FOLDS, VAL_FOLDS, TEST_FOLDS = range(0, 7), [7], [8, 9]
SPLIT_COLUMNS = ["isic_id", "split", "label", "group_id", "lesion_id", "patient_id",
                 "diagnosis_1", "diagnosis_2", "diagnosis_3", "attribution"]


def connected_groups(df: pd.DataFrame, keys=("lesion_id", "patient_id")) -> pd.Series:
    """Union-find over images: images sharing any non-null key end up in the same group."""
    parent = list(range(len(df)))

    def find(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    for key in keys:
        for _, idx in df.groupby(key, dropna=True).indices.items():
            root = find(idx[0])
            for j in idx[1:]:
                parent[find(j)] = root

    roots = [find(i) for i in range(len(df))]
    # stable, human-readable group ids: G + index of the group's first image in isic_id order
    first = {}
    return pd.Series([f"G{first.setdefault(r, len(first)):05d}" for r in roots], index=df.index)


def make_split(meta: pd.DataFrame, seed: int = SEED) -> pd.DataFrame:
    df = meta.sort_values("isic_id").reset_index(drop=True).copy()
    df["label"] = df["diagnosis_1"].map(LABEL_MAP)
    df["group_id"] = connected_groups(df)
    df["split"] = "excluded"

    labelled = df[df["label"].notna()]
    sgkf = StratifiedGroupKFold(n_splits=10, shuffle=True, random_state=seed)
    fold = pd.Series(-1, index=labelled.index)
    for k, (_, test_idx) in enumerate(sgkf.split(labelled, labelled["label"], labelled["group_id"])):
        fold.iloc[test_idx] = k

    df.loc[fold.index[fold.isin(TRAIN_FOLDS)], "split"] = "train"
    df.loc[fold.index[fold.isin(VAL_FOLDS)], "split"] = "val"
    df.loc[fold.index[fold.isin(TEST_FOLDS)], "split"] = "test"
    df["label"] = df["label"].astype("Int64")
    return df[SPLIT_COLUMNS]


def old_image_level_split(meta: pd.DataFrame) -> pd.DataFrame:
    """Re-creates uncertaintyNet dataset.py (MEDIRV2) splitting logic for a leakage comparison.
    Row order of the original metadata.csv is unknown, so isic_id order is used."""
    df = meta.sort_values("isic_id").reset_index(drop=True).copy()
    df["label"] = df["diagnosis_1"].map(LABEL_MAP)
    df = df.dropna(subset=["label"])
    X, y = df.index.values, df["label"].values
    X_train, X_temp, _, y_temp = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
    X_val, X_test, _, _ = train_test_split(X_temp, y_temp, test_size=2 / 3, random_state=42, stratify=y_temp)
    df["split"] = "train"
    df.loc[X_val, "split"] = "val"
    df.loc[X_test, "split"] = "test"
    df["group_id"] = connected_groups(df)
    return df


def leakage(df: pd.DataFrame) -> dict:
    """Share of val/test images whose group (same lesion or patient) also has a train image."""
    train_groups = set(df.loc[df["split"] == "train", "group_id"])
    out = {}
    for split in ("val", "test"):
        part = df[df["split"] == split]
        shared = part["group_id"].isin(train_groups)
        out[split] = (int(shared.sum()), len(part))
    return out


def report(split: pd.DataFrame, old: pd.DataFrame) -> str:
    lines = ["# ISIC clinical close-up split v1", "",
             f"Generated by `splits/make_isic_clinical_split.py` (seed {SEED}). "
             "Groups = connected components of shared `lesion_id` or `patient_id`.", ""]
    counts = pd.crosstab(split["split"], split["diagnosis_1"].fillna("(missing)"), margins=True)
    lines += ["## Images per split", "", counts.to_markdown(), ""]
    labelled = split[split["split"] != "excluded"]
    share = labelled.groupby("split")["label"].agg(["count", "mean"]).rename(columns={"mean": "malignant_share"})
    lines += ["## Class balance", "", share.round(3).to_markdown(), ""]
    groups = split.groupby("group_id").size()
    lines += ["## Groups", "",
              f"- {split['group_id'].nunique()} groups for {len(split)} images; "
              f"{(groups > 1).sum()} groups contain >1 image ({groups[groups > 1].sum()} images); largest = {groups.max()}.",
              f"- Group leakage across train/val/test in v1: **{sum(n for n, _ in leakage(split).values())} images** (must be 0).", ""]
    old_leak = leakage(old)
    lines += ["## Leakage in the previous image-level split (dataset.py MEDIRV2, isic_id order)", "",
              f"- val: {old_leak['val'][0]}/{old_leak['val'][1]} images share a lesion/patient with train "
              f"({old_leak['val'][0] / old_leak['val'][1]:.1%})",
              f"- test: {old_leak['test'][0]}/{old_leak['test'][1]} images share a lesion/patient with train "
              f"({old_leak['test'][0] / old_leak['test'][1]:.1%})", ""]
    dx3 = pd.crosstab(labelled["diagnosis_3"].fillna("(missing)"), labelled["split"])
    dx3 = dx3.loc[dx3.sum(axis=1).sort_values(ascending=False).index].head(15)
    lines += ["## Top diagnosis_3 classes per split (for one-vs-all models)", "", dx3.to_markdown(), ""]
    src = pd.crosstab(labelled["attribution"], labelled["split"])
    lines += ["## Source (attribution) per split", "", src.to_markdown(), ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    here = Path(__file__).resolve().parent
    parser.add_argument("--metadata", default=str(here / "isic_clinical_closeup_metadata.csv"))
    parser.add_argument("--out", default=str(here / "isic_clinical_v1.csv"))
    opts = parser.parse_args()

    meta = pd.read_csv(opts.metadata, low_memory=False)
    split = make_split(meta)
    assert sum(n for n, _ in leakage(split).values()) == 0, "group leakage in new split"
    split.to_csv(opts.out, index=False)
    Path(opts.out).with_name(Path(opts.out).stem + "_report.md").write_text(
        report(split, old_image_level_split(meta)), encoding="utf-8")
    print(split["split"].value_counts().to_dict())
    print("leakage (new):", leakage(split), "| leakage (old image-level):", leakage(old_image_level_split(meta)))
